source ~/.vim/options.vim
source ~/.vim/keybinds.vim
source ~/.vim/plugins.vim
source ~/.vim/fzf.vim
source ~/.vim/lightline.vim
source ~/.vim/auto_pairs.vim
source ~/.vim/colors.vim
source ~/.vim/async_complete.vim
source ~/.vim/nerdtree.vim
source ~/.vim/outline.vim
source ~/.vim/bookmark.vim
